server:
  port: 80
spring:
  application:
    name: atcrowd-member-zuul
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #配置路由规则
        - id: payment_routh      #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://ATCROWD-MEMBER-AUTHENTICATION-CONSUMER  #匹配后提供服务的路由地址
          predicates: #配置断言规则
            - Path=/**         # 断言，路径相匹配的进行路由
  redis:
     host: 192.168.132.10
  # springsession 配置
  session:
     store-type: redis

eureka:
  client:
    #是否将自己注册到Eureka中默认是true
    register-with-eureka: true
    #是否从何Eureka抓取已有的注册信息，默认是true。单机版无所谓，集群版必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #注册中心的地址
      defaultZone: http://localhost:1000/eureka
  instance:
    instance-id: authentication-consumer80
    prefer-ip-address: true #显示ip地址
