server:
  port: 2000
spring:
  application:
    name: atcrowd-member-mysql-provider
  datasource:
    url: jdbc:mysql://localhost:3306/project_crowd
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    #是否将自己注册到Eureka中默认是true
    register-with-eureka: true
    #是否从何Eureka抓取已有的注册信息，默认是true。单机版无所谓，集群版必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #注册中心的地址
      defaultZone: http://localhost:1000/eureka
  instance:
      instance-id: mysql-provider2000
      prefer-ip-address: true #显示ip地址
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml  加载全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #使用配置的方式配置mybatis
logging:
  level:
    com.atguigu.atcrowdfunding.mapper: debug
    com.atguigu.atcrowdfunding.test: debug
